= XebiaLabs DevOps Platform docker images
Author: XebiaLabs Development Team
:executable: ./xldocker.py
:source-highligher: pygments

== Prerequisites
If you want to generate Dockerfiles for new versions of the XebiaLabs DevOps platform, or build a container out of them using the script provided, you need to setup your Python environment.
To make this easy we've provided a `Pipfile` that contains the necessary dependencies for the Python build scripts. To install these, you can use the link:https://docs.pipenv.org/[`pipenv`] command line tool.

You can install this on Mac using Brew:

[source,shell]
----
$ brew install pipenv
----

Or you can install this using regular Pyton pip:

[source,shell]
----
$ pip install --user pipenv
----

After you've installed `pipenv` just execute:

[source,shell]
----
$ pipenv install
$ pipenv shell
----

This will install all the dependencies and activate the `virtualenv` containing all the installed dependencies.


== Generating the Dockerfiles for a new version of the XebiaLabs DevOps Platform
In order to generate a new set of Dockerfiles for all components of the XebiaLabs DevOps Platform and commit them to version control, you can execute the following command:

[source,shell,subs="verbatim,attributes"]
----
$ {executable} render --xl-version <version> --commit
----

If you want to generate the Dockerfiles for a specific components of the XebiaLabs DevOps Platform, you can execute the following command:

[source,shell,subs="verbatim,attributes"]
----
$ {executable} render --xl-version <version> --product {xl-deploy,xl-release}
----

If you want to generate an updated set of Dockerfiles for an already released version of the XebiaLabs DevOps Platform, the following command will generate a version tag of `<version>-<suffix>`:

[source,shell,subs="verbatim,attributes"]
----
$ {executable} render --xl-version <version> --suffix <number>
----
