version: "2"
services:
  xl-deploy:
    image: xebialabs/xl-deploy:10.1
    container_name: xl-deploy
    ports:
     - "4516:4516"
    volumes:
     - xld:/opt/xebialabs/xl-deploy-server
    environment:
     - ADMIN_PASSWORD=admin
     - ACCEPT_EULA=Y

  xl-release:
    image: xebialabs/xl-release:10.1
    container_name: xl-release
    ports:
     - "5516:5516"
    links:
     - xl-deploy
    volumes:
     - xlr:/opt/xebialabs/xl-release-server
    environment:
     - ADMIN_PASSWORD=admin
     - ACCEPT_EULA=Y
volumes:
  xlr:
  xld:
