version: "2"
services:
  xl-deploy:
    image: xebialabs/xl-deploy:10.0
    container_name: xl-deploy
    ports:
     - "4516:4516"
    volumes:
     - ~/XebiaLabs/xl-deploy-server/conf:/opt/xebialabs/xl-deploy-server/conf
     - ~/XebiaLabs/xl-deploy-server/ext:/opt/xebialabs/xl-deploy-server/ext
     - ~/XebiaLabs/xl-deploy-server/hotfix/lib:/opt/xebialabs/xl-deploy-server/hotfix/lib
     - ~/XebiaLabs/xl-deploy-server/hotfix/plugins:/opt/xebialabs/xl-deploy-server/hotfix/plugins
     - ~/XebiaLabs/xl-deploy-server/plugins:/opt/xebialabs/xl-deploy-server/plugins
     - ~/XebiaLabs/xl-deploy-server/repository:/opt/xebialabs/xl-deploy-server/repository
    environment:
     - ADMIN_PASSWORD=admin
     - ACCEPT_EULA=Y

  xl-release:
    image: xebialabs/xl-release:10.0
    container_name: xl-release
    ports:
     - "5516:5516"
    links:
     - xl-deploy
    volumes:
     - ~/XebiaLabs/xl-release-server/conf:/opt/xebialabs/xl-release-server/conf
     - ~/XebiaLabs/xl-release-server/ext:/opt/xebialabs/xl-release-server/ext
     - ~/XebiaLabs/xl-release-server/hotfix/:/opt/xebialabs/xl-release-server/hotfix/
     - ~/XebiaLabs/xl-release-server/plugins:/opt/xebialabs/xl-release-server/plugins
     - ~/XebiaLabs/xl-release-server/repository:/opt/xebialabs/xl-release-server/repository
     - ~/XebiaLabs/xl-release-server/archive:/opt/xebialabs/xl-release-server/archive
    environment:
     - ADMIN_PASSWORD=admin
     - ACCEPT_EULA=Y
