FROM alpine:3.13.0 as installer

# Install dependencies
RUN apk add --no-cache gawk unzip curl

{% if 'central-config' in product %}
    {% include './central-config/install.j2' %}
{% else %}
    {% include 'install.j2' %}
{% endif %}

FROM centos:7

{% include 'metadata.j2' %}

{% include 'variables.j2' %}

# Install dependencies
RUN yum update -y && \
    yum install -y epel-release && \
    yum install -y java-11-openjdk-devel curl jq unzip which && \
    yum clean all -q

# Copy installed {{ product_name }}
COPY --from=installer ${APP_ROOT} ${APP_ROOT}

ENV OS=centos

{% if 'deploy' in product %}
    {% include 'terraform.j2' %}
{% endif %}

{% include 'runtime.j2' %}
