FROM alpine:3.12 as installer

# Install dependencies
RUN apk add --no-cache gawk unzip curl

{% include 'install.j2' %}

FROM centos:7

{% include 'metadata.j2' %}

{% include 'variables.j2' %}

# Install dependencies
RUN yum update -y && \
    yum install -y epel-release && \
    yum install -y java-1.8.0-openjdk-headless curl jq unzip which && \
    yum clean all -q

# Copy installed {{ product_name }}
COPY --from=installer ${APP_ROOT} ${APP_ROOT}

ENV OS=centos

{% if 'deploy' in product %}
    {% include 'terraform.j2' %}
{% endif %}

{% include 'runtime.j2' %}
