name: central-configuration
dockerfiles:
  default: 'ubuntu'
  os:
    debian-slim: debian-slim/Dockerfile.j2
    centos: centos/Dockerfile.j2
    amazonlinux: amazonlinux/Dockerfile.j2
    rhel: rhel/Dockerfile.j2
    ubuntu: ubuntu/Dockerfile.j2
repositories:
  nexus: 'https://nexus.xebialabs.com/nexus/service/local/repositories/{repo}/content/ai/digital/config/central-configuration-server/{version}/{product}-server-{version}.zip'
  dist: 'https://dist.xebialabs.com/customer/central-configuration-server/product/{version}/{product}-server-{version}.zip'
  localm2: 'ai/digital/config/central-configuration-server/{version}/{product}-server-{version}.zip'
resources:
  target_name: '{product}-{version}-server.zip'
  dirs:
    - all
    - common
    - central-configuration
    - deploy-central-configuration
context:
  license_server: https://download.xebialabs.com
  product: central-configuration
  product_name: Central configuration
  product_description: Enterprise-scale Application Release Automation for any environment
  boot_conf: deployit.conf
  wrapper_conf: xlc-wrapper.conf.common
  central_config_files:
    - deploy-cluster.yaml
    - deploy-metrics.yaml
    - deploy-oidc.yaml
    - deploy-plugins.yaml
    - deploy-repository.yaml
    - deploy-reporting.yaml
    - deploy-satellite.yaml
    - deploy-secret-complexity.yaml
    - deploy-server.yaml
    - deploy-task.yaml
    - deploy-caches.yaml
  port: 8888
  volumes:
    - "${APP_HOME}/conf"
    - "${APP_HOME}/centralConfiguration"
  environment:
    - key: XL_CLUSTER_MODE
      value: default
    - key: XL_DB_URL
      value: "jdbc:derby:repository/db;create=true"
    - key: XL_DB_USERNAME
      value: sa
    - key: XL_DB_PASSWORD
      value: "123"
    - key: XL_DB_MAX_POOL_SIZE
      value: 10
    - key: XL_REPORT_DB_URL
      value: "jdbc:derby:repository/db-report;create=true"
    - key: XL_REPORT_DB_USERNAME
      value: sa
    - key: XL_REPORT_DB_PASSWORD
      value: "123"
    - key: XL_REPORT_DB_MAX_POOL_SIZE
      value: 10
    - key: XL_METRICS_ENABLED
      value: "false"
    - key: XLD_IN_PROCESS
      value: "true"
    - key: XLD_TASK_QUEUE_NAME
      value: "xld-tasks-queue"
    - key: XLD_TASK_QUEUE_IN_PROCESS_MAX_DISK_USAGE
      value: "100"
    - key: XLD_TASK_QUEUE_IN_PROCESS_SHUTDOWN_TIMEOUT
      value: "60000"
    - key: XLD_TASK_QUEUE_DRIVER_CLASS_NAME
      value: ""
    - key: XLD_TASK_QUEUE_URL
      value: ""
    - key: XLD_TASK_QUEUE_USERNAME
      value: ""
    - key: XLD_TASK_QUEUE_PASSWORD
      value: ""
    - key: HOSTNAME_SUFFIX
      value: ""
    - key: XL_LICENSE_KIND
      value: byol
    - key: GENERATE_XL_CONFIG
      value: "true"
    - key: USE_IP_AS_HOSTNAME
      value: "false"
    - key: ENABLE_SATELLITE
      value: "false"
    - key: CENTRAL_CONFIG_ENCRYPT_KEY
      value: ""
    - key: USE_CACHE
      value: "false"
    - key: LOGBACK_GLOBAL_LOGGING_LEVEL
      value: "info"
    - key: LOGBACK_SCAN_ENABLED
      value: "true"
    - key: LOGBACK_SCAN_PERIOD
      value: "30seconds"
