FROM alpine:3.12 as installer

# Install dependencies
RUN apk add --no-cache gawk unzip curl

{% include 'install.j2' %}

FROM amazonlinux:2

{% include 'metadata.j2' %}

{% include 'variables.j2' %}

# Install dependencies
RUN yum update -y && \
    yum install -y java-11-amazon-corretto curl jq shadow-utils.x86_64 hostname unzip which && \
    yum clean all -q

# Copy installed {{ product_name }}
COPY --from=installer ${APP_ROOT} ${APP_ROOT}

ENV OS=amazonlinux

{% if 'deploy' in product %}
    {% include 'terraform.j2' %}
{% endif %}

{% include 'runtime.j2' %}
