FROM alpine:3.16 as installer

# Install dependencies
RUN apk update
RUN apk add --no-cache gawk unzip curl busybox-extras

{% if 'deploy-task-engine' in product %}
    {% include './deploy-task-engine/install.j2' %}
{% elif 'central-config' in product %}
    {% include './central-configuration/install.j2' %}
{% else %}
    {% include 'install.j2' %}
{% endif %}

FROM amazonlinux:2

{% include 'metadata.j2' %}

{% if 'deploy-task-engine' in product %}
    {% include './deploy-task-engine/variables.j2' %}
{% else %}
    {% include 'variables.j2' %}
{% endif %}

# Install dependencies
RUN yum update -y && \
    yum install -y java-11-amazon-corretto curl jq shadow-utils.x86_64 hostname unzip which telnet && \
    yum clean all -q

# Copy installed {{ product_name }}
COPY --from=installer ${APP_ROOT} ${APP_ROOT}

ENV OS=amazonlinux

{% if 'deploy' in product %}
    {% include 'terraform.j2' %}
{% endif %}

{% include 'runtime.j2' %}
