FROM alpine:3.22 as installer

# Install dependencies
RUN apk update
RUN apk add --no-cache gawk unzip curl busybox-extras

{% if 'deploy-task-engine' in product %}
    {% include './deploy-task-engine/install.j2' %}
{% elif 'central-config' in product %}
    {% include './central-configuration/install.j2' %}
{% else %}
    {% include 'install.j2' %}
{% endif %}

FROM amazonlinux:2

{% include 'metadata.j2' %}

{% if 'deploy-task-engine' in product %}
    {% include './deploy-task-engine/variables.j2' %}
{% else %}
    {% include 'variables.j2' %}
{% endif %}

# Install dependencies
RUN yum update -y && \
{% if xl_version.startswith('26.3') and image_version.endswith('-jdk25') %}
    yum install -y java-25-amazon-corretto curl jq shadow-utils.x86_64 hostname unzip which telnet && \
{% else %}
    yum install -y java-21-amazon-corretto curl jq shadow-utils.x86_64 hostname unzip which telnet && \
{% endif %}
    yum clean all -q

# Copy installed {{ product_name }}
COPY --from=installer ${APP_ROOT} ${APP_ROOT}

ENV OS=amazonlinux

{% include 'runtime.j2' %}
