FROM alpine:3.14.2 as installer

ENV USER_UID=10001 APP_ROOT=/opt/xebialabs
ENV APP_HOME=${APP_ROOT}/{{ product }}

COPY resources/{{ product }}-{{ xl_version }}-linux-amd64.bin /tmp

RUN mkdir -p ${APP_HOME} && \
    mv /tmp/{{ product }}-{{ xl_version }}-linux-amd64.bin ${APP_HOME}/xl && \
    chgrp -R 0 ${APP_ROOT} && \
    chmod -R g=u ${APP_ROOT} && \
    chmod g+x ${APP_HOME}/xl


FROM alpine:3.14.2

{% include 'metadata.j2' %}

ENV USER_UID=10001 APP_ROOT=/opt/xebialabs
ENV APP_HOME=${APP_ROOT}/{{ product }}

# Copy installed {{ product_name }}
COPY --from=installer ${APP_ROOT} ${APP_ROOT}

COPY resources/amd64/tini /opt
RUN chmod ugo+x /opt/tini

WORKDIR ${APP_HOME}

# Don't run as root
USER 10001

ENTRYPOINT ["/opt/tini", "/opt/xebialabs/{{ product }}/xl"]
