FROM alpine:3.7 as installer

# Install dependencies
RUN apk add --no-cache gawk unzip curl

{% include 'install.j2' %}

FROM openjdk:8-jdk-slim-stretch

{% include 'metadata.j2' %}

{% include 'variables.j2' %}

# Copy installed {{ product_name }}
COPY --from=installer ${APP_ROOT} ${APP_ROOT}

ENV OS=debian

{% include 'runtime.j2' %}
