FROM alpine:3.13.0 as installer

# Install dependencies
RUN apk add --no-cache gawk unzip curl

{% include 'install.j2' %}

FROM openjdk:11-jdk-slim-buster

{% include 'metadata.j2' %}

{% include 'variables.j2' %}

# Install dependencies
RUN apt-get update -y && \
    apt-get install -y curl jq unzip apt-utils&& \
    apt-get clean all -q

# Copy installed {{ product_name }}
COPY --from=installer ${APP_ROOT} ${APP_ROOT}

ENV OS=debian

{% if 'deploy' in product %}
    {% include 'terraform.j2' %}
{% endif %}

{% include 'runtime.j2' %}
