version: "3"
services:
  xl-deploy-worker:
    image: xebialabs/deploy-task-engine:10.4 # deploy-task-engine is not yet released on the xebialabs repo
    networks:
      - xld-network
    environment:
      - USE_IP_AS_HOSTNAME=true
      - ADMIN_PASSWORD=${XLD_ADMIN_PASS}
      - ACCEPT_EULA=Y
      - XL_CLUSTER_MODE=default
      - XLD_IN_PROCESS=false
      - XLD_TASK_QUEUE_DRIVER_CLASS_NAME=com.rabbitmq.jms.admin.RMQConnectionFactory
      - XLD_TASK_QUEUE_URL=amqp://rabbitmq:5672
      - XLD_TASK_QUEUE_USERNAME=rabbitmq
      - XLD_TASK_QUEUE_PASSWORD=${RABBITMQ_PASS}
      - XL_DB_URL=jdbc:postgresql://postgresql:5432/xld-db
      - XL_DB_USERNAME=postgres
      - XL_DB_PASSWORD=${POSTGRES_PASS}
      #- XL_LICENSE=YOUR_LICENSE_IN_BASE64_STRING
    command:
      - "-api"
      - "http://${XLD_LB}:5000/"
      - "-master"
      - "${XLD_MASTER_1}:8180"
      - "-master"
      - "${XLD_MASTER_2}:8180"
    volumes:
      - $PWD/xl-deploy-worker/conf:/opt/xebialabs/deploy-task-engine/conf # provide deployit-licence.lic file in the conf folder
      - $PWD/xl-deploy-worker/plugins:/opt/xebialabs/deploy-task-engine/plugins

networks:
  xld-network:
    external: true
